# Generated by Django 5.1.4 on 2025-01-13 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("annotations", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="annotation",
            name="position",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
