# Generated by Django 5.1.4 on 2025-01-15 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("annotations", "0002_alter_annotation_position"),
    ]

    operations = [
        migrations.AddField(
            model_name="annotation",
            name="order",
            field=models.IntegerField(default=0),
        ),
    ]
